d-test-git-pull/django-doc-polls-app/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/",include("polls.urls")),

]

d-test-git-pull/django-doc-polls-app/polls/urls.py
from django.urls import path
from . import views
app_name = "polls"
'''urlpatterns=[
    # ex: /polls/
    path("", views.index, name="index"),
    # ex: /polls/5/
    path("<int:question_id>/", views.detail, name="detail"),
    # ex: /polls/5/results/
    path("<int:question_id>/results/", views.results, name="results"),
    # ex: /polls/5/vote/
    path("<int:question_id>/vote/", views.vote, name="vote"),
]'''
urlpatterns = [
    path("", views.IndexView.as_view(), name="index"),
    path("<int:pk>/", views.DetailView.as_view(), name="detail"),
    path("<int:pk>/results/", views.ResultsView.as_view(), name="results"),
    path("<int:question_id>/vote/", views.vote, name="vote"),
    path("form/",views.form_req,name="form_url")
]

d-test-git-pull/django-doc-polls-app/polls/models.py
import datetime
from django.db import models
from django.utils import timezone

# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField("date published")
    def __str__(self):
        return self.question_text
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
        #return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    def __str__(self):
        return self.choice_text

d-test-git-pull/django-doc-polls-app/polls/views.py
from django.http import HttpResponseRedirect,HttpResponse,JsonResponse
from django.shortcuts import get_object_or_404, render
from django.urls import reverse
from django.views import generic
from django.utils import timezone
from .models import Choice, Question
import requests
import json
def form_req(request):
    template='polls/forms.html'
    content={'val':'he','questions':None}
    if request.method=='GET':
        print("in get :")
        return render(request,template,content)
    print(request.method)
    if request.method == 'POST':
        print("in post :")
        content['val']=request.POST['the choice']
        content['questions']=Question.objects.filter(choice__choice_text=content['val'])
        print(content["questions"])
        res=requests.get('https://api.geoapify.com/v1/geocode/search?city={}&format=json&apiKey=d0f637b5187e487196dd3d9504742ecf'.format(content['val']))
        dict_res=res.json()
        '''print(dict_res.keys(),dict_res)
        for key in dict_res.keys():
            print(type(dict_res[key]))
        for data in dict_res['results'][0]:
            print(data,'\n',type(data))'''
        lat=dict_res['results'][0]['lat']
        lon=dict_res['results'][0]['lon']
        print(lat,lon)
        return render(request,template,content)
        '''print(type(request.POST),'req')
        res=request.POST
        key=res.keys()
        value=res.values()
        res=dict(zip(list(res.keys())[1:],list(res.values())[1:]))
        return JsonResponse(res)
        print(json.dumps(request))
        print(request.POST)
        return HttpResponse(f"jghyu{json.dumps(request.POST)}")'''
        
    #return render(request,'polls/forms.html')
class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        '''"""Return the last five published questions."""
        return Question.objects.order_by("-pub_date")[:5]
        '''
        """
        Return the last five published questions (not including those set to be
        published in the future).
        """
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by("-pub_date")[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"

def vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST["choice"])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(
            request,
            "polls/detail.html",
            {
                "question": question,
                "error_message": "You didn't select a choice.",
            },
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse("polls:results", args=(question.id,)))
    """
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import Choice, Question
from django.urls import reverse
# Create your views here.
def index(request):
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    template = loader.get_template("polls/index.html")
    context = {
        "latest_question_list": latest_question_list,
    }
    return HttpResponse(template.render(context, request))
'''
def detail(request, question_id):
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, "polls/detail.html", {"question": question})
'''
def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/detail.html", {"question": question})
    

def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/results.html", {"question": question})

    """

d-test-git-pull/django-doc-polls-app/polls/templates/polls/detail.html
<form action="{% url 'polls:vote' question.id %}" method="post">
  <!---->>
    <fieldset>
        <legend><h1>{{ question.question_text }}</h1></legend>
        {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
        {% for choice in question.choice_set.all %}
            <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
        {% endfor %}
    </fieldset>
    <input type="submit" value="Vote">
</form>

d-test-git-pull/django-doc-polls-app/polls/templates/polls/forms.html
<form action="{%url 'polls:form_url' %}" method="post">
    {% csrf_token %}
    <label for="qn">enter the choice:</label>
    <input type="text" name="the choice" id="qn" value="{{val}}">
    <input type="submit" value="submit">
    {%if val != 'he'%}
    {%if questions != None and questions|length != 0 %}
        <p>{{questions|length}}</p>
        <h3>The queations with "{{val}}" as choice are:</h3>
       
        <table>
            <tr>
                <th>question</th>
                <th>date published</th>
            </tr>
            {%for ques in questions%}
            <tr>
                <td>{{ques.question_text}}</td>
                <td>{{ques.pub_date}}</td>
            </tr>
            {%endfor%}
        </table>

    {%else %}
    <p>No question found. Please try again!</p>
    {%endif%}
    {%endif%}
</form>

d-test-git-pull/django-doc-polls-app/polls/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
    <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

d-test-git-pull/django-doc-polls-app/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>